/**
 * 长文档处理策略 — sliding window + summary chain.
 *
 * When an input exceeds the agent's effective context window,
 * split into overlapping chunks, summarize each, then chain
 * summaries into a final digest.
 *
 * Architecture:
 *   Input → Chunk(sliding window) → Per-chunk Summary → Chain → Final Digest
 *
 * All summaries are generated by the calling agent's LLM, so quality
 * depends on the model in use. The chunker is pure text processing
 * and works without any LLM call.
 */

import type { BaseAgent } from "./agent";

/* ═══════════════════════════════════════
   Chunker — split text into overlapping windows
   ═══════════════════════════════════════ */
export interface ChunkOptions {
  /** Target chunk size in characters (default 6000) */
  chunkSize?: number;
  /** Overlap between consecutive chunks in characters (default 800) */
  overlap?: number;
  /** Minimum chunk size before we stop splitting (default 500) */
  minChunk?: number;
}

export function chunkText(text: string, opts?: ChunkOptions): string[] {
  const cs = opts?.chunkSize ?? 6000;
  const ol = opts?.overlap ?? 800;
  const min = opts?.minChunk ?? 500;
  const chunks: string[] = [];

  if (text.length <= cs + min) { chunks.push(text); return chunks; }

  let start = 0;
  while (start < text.length) {
    let end = start + cs;
    if (end >= text.length) { end = text.length; }
    else {
      // Try to break at paragraph boundary
      const searchEnd = Math.min(end + 400, text.length);
      const paraBreak = text.lastIndexOf("\n\n", searchEnd);
      if (paraBreak > start + min) end = paraBreak;
      else {
        const lineBreak = text.lastIndexOf("\n", searchEnd);
        if (lineBreak > start + min) end = lineBreak;
        else {
          const space = text.lastIndexOf(" ", searchEnd);
          if (space > start + min) end = space;
        }
      }
    }

    chunks.push(text.slice(start, end).trim());
    if (end >= text.length) break;
    start = end - ol;
    if (start < 0) start = 0;
  }

  return chunks;
}

/* ═══════════════════════════════════════
   Summary chain — ask agent to summarize chunks then chain
   ═══════════════════════════════════════ */
export interface SummaryOptions {
  /** Max total chars for the final digest (default 3000) */
  maxDigestChars?: number;
  /** Custom summarization prompt for each chunk */
  chunkPrompt?: string;
  /** Custom chain prompt for combining summaries */
  chainPrompt?: string;
}

const DEFAULT_CHUNK_PROMPT = `Summarize the following text concisely. Keep all key facts, names, numbers, and code snippets. Output the summary directly without preamble. Limit to 300 words.

Text:
{text}`;

const DEFAULT_CHAIN_PROMPT = `Combine the following section summaries into a single coherent digest. Preserve all key facts, remove redundancy. Output directly without preamble.

{summaries}`;

export async function summarizeLongDoc(
  agent: BaseAgent,
  text: string,
  opts?: SummaryOptions
): Promise<string> {
  const maxDigest = opts?.maxDigestChars ?? 3000;
  const chunks = chunkText(text);

  // Single chunk — no summarization needed
  if (chunks.length <= 1) {
    if (text.length <= maxDigest) return text;
    const prompt = (opts?.chunkPrompt || DEFAULT_CHUNK_PROMPT).replace("{text}", text);
    return agent.chatOneshot(prompt, { maxTokens: maxDigest });
  }

  // Multi-chunk: summarize each, then chain
  const summaries: string[] = [];
  for (let i = 0; i < chunks.length; i++) {
    const prompt = (opts?.chunkPrompt || DEFAULT_CHUNK_PROMPT).replace("{text}", chunks[i]);
    try {
      const s = await agent.chatOneshot(prompt, { maxTokens: 600 });
      summaries.push(s);
    } catch {
      summaries.push(chunks[i].slice(0, 400) + "...");
    }
  }

  // Chain summaries
  if (summaries.length === 1) return summaries[0].slice(0, maxDigest);

  const joined = summaries.map((s, i) => `## Section ${i + 1}\n${s}`).join("\n\n");
  if (joined.length <= maxDigest) return joined;

  const chainPrompt = (opts?.chainPrompt || DEFAULT_CHAIN_PROMPT).replace("{summaries}", joined);
  const final = await agent.chatOneshot(chainPrompt, { maxTokens: maxDigest });
  return final.slice(0, maxDigest);
}

/* ═══════════════════════════════════════
   Structured data parsing helpers
   ═══════════════════════════════════════ */
export function parseStructuredInput(input: string): {
  hasTable: boolean; hasJSON: boolean; hasCSV: boolean;
  extractedJSON: string | null; extractedTable: string[][] | null;
} {
  const result = { hasTable: false, hasJSON: false, hasCSV: false, extractedJSON: null as string | null, extractedTable: null as string[][] | null };

  // Detect JSON
  const jsonMatch = input.match(/\{[\s\S]*\}|\[[\s\S]*\]/);
  if (jsonMatch) {
    try { JSON.parse(jsonMatch[0]); result.hasJSON = true; result.extractedJSON = jsonMatch[0]; }
    catch { /* not valid JSON */ }
  }

  // Detect markdown table
  const tableMatch = input.match(/\|[\s\S]*?\|/);
  if (tableMatch) {
    result.hasTable = true;
    const lines = input.split("\n").filter(l => l.includes("|") && !l.startsWith("|---") && !l.startsWith("| --"));
    result.extractedTable = lines.map(l => l.split("|").filter(c => c.trim()).map(c => c.trim()));
  }

  // Detect CSV
  if (input.includes(",") && input.split("\n").filter(l => l.includes(",")).length >= 2) {
    result.hasCSV = true;
  }

  return result;
}
